# Generated by Django 4.0.6 on 2022-08-12 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
                ('emial', models.EmailField(max_length=100)),
                ('edad', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
                ('emial', models.EmailField(max_length=100)),
                ('cargo', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='perfiles',
        ),
        migrations.AlterField(
            model_name='bicicletas',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
