# Generated by Django 4.0.6 on 2022-08-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnviarMensajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=30)),
                ('telefono', models.CharField(max_length=30)),
                ('mensaje', models.CharField(max_length=100)),
            ],
        ),
    ]
