# Generated by Django 4.0.6 on 2022-08-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appventas', '0002_cliente_empleado_delete_perfiles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='accesorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
    ]
